version: "3.7"
#in devop we call services not appli
services:
  mypostgres:
    image: postgres
    container_name: mypostgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "ticketing-app"
    ports:
      - "5435:5432"
    restart: always
    networks:
      - webnet
    volumes:
      - initdb:/var/lib/postgresql/data


  ticketing-app:
    build: .
    container_name: ticketingapp
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - mypostgres

networks:
  webnet:
    driver: bridge

volumes:
  initdb:

